import { AreaChartOutlined } from '@ant-design/icons';

export default {
  profile: null,
  project: null,
  snippets: null,
  apartment: null,
  book: null,
  menu: null,
  edit: null,
  audit: null,
  container: null,
  "area-chart\t": <AreaChartOutlined />,
  import: null,
  control: null,
  "unordered-list": null,
  "question-circle": null,
  dashboard: null,
  copy: null,
  diff: null,
  "bar-chart": null,
  "ordered-list": null,
  bell: null,
  bank: null,
  user: null,
  desktop: null,
  database: null,
  search: null,
  hdd: null,
  wallet: null,
  "dot-chart": null,
  "info-circle": null,
  safety: null,
  link: null,
  appstore: null,
};
